#+HTML:<div align=center><a href="https://github.com/hatlafax/psimacs"><img alt="Emacs Logo" width="240" height="240" src="https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg"></a>

* psimacs - Yet another Emacs configuration

[[https://github.com/hatlafax/psimacs][https://img.shields.io/badge/Psimacs-0.1-red.svg?style=plastic]]
[[https://www.gnu.org/software/emacs/][https://img.shields.io/badge/GNU%20Emacs-27.2-green.svg?style=plastic]]
[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg?style=plastic]]

#+HTML:</div>

This is an attempt to create a /modern/ *Emacs* configuration from the ground up. It has the following objectives:

- Use of modern packages and styles. It should be an *Emacs* of the 21. century.
- Literally programming style. The complete configuration is written in one [[https://orgmode.org/][org-mode]] file.
- Primarily target Windows operating system. The reason is that I am solely work on Windows and so I do not
  know much about the details of other systems.
- Simple to use.
- [[https://github.com/raxod502/straight.el][Straight]] package manager.
- Support of [[https://www.dropbox.com/][Dropbox]] configuration sharing.
- No [[https://github.com/emacs-evil/evil][evil]]. Probably a very good package, that many people do like. However, I am trained with the classic
  *Emacs* keyboard handling and I am used to it.
- Use of [[https://github.com/justbur/emacs-which-key][which-key]]. This is a game changer for me.
- Use of [[https://github.com/abo-abo/hydra][hydra]]. And another beautiful package that I like a lot.
- Use of [[https://github.com/abo-abo/swiper][ivy]]. I started with ivy and I am quite comfortable with it. Likely, [[https://www.gnu.org/software/emacs/manual/html_mono/ido.html][ido]] and  [[https://github.com/emacs-helm/helm][helm]] are also worth trying.
- Use of [[https://github.com/bbatsov/projectile][projectile]]. Another great package that I am used to.
- Use of [[http://company-mode.github.io/][company]]. Great text completion framework.
- Use of [[https://github.com/peter-milliken/ELSE][ELSE]] for programming.
- Use of [[https://github.com/joaotavora/yasnippet][yasnippet]].
- Focus on org, programming and [[https://www.gnu.org/software/auctex/][LaTeX]] text writing.
- And many, many more...

* Motivation

A lot of *Emacs* configurations can be found on the Internet. Many of them are well crafted and could be used out of
the box. Especially, the great *Emacs* distributions like [[https://www.spacemacs.org/][Spacemacs]], [[https://github.com/hlissner/doom-emacs][Doom-Emacs]] and [[https://github.com/seagle0128/.emacs.d][Centaur-Emacs]] are worth giving a try.
But I wanted to craft my own configuration that is tailored to my needs and that allowed me to learn more about the
vast *Emacs* universe. My configuration it not perfect for everyone and it will not be able to compete against the big
frameworks that are build by a lot of talented people. So feel free to use it or blame it. I am fine with it.

The name *Psimacs* is arbitrarily. I was in search for a catchy name with just one syllable in front of the *macs*.

* Installation

At first, install [[https://www.gnu.org/software/emacs/download.html][Emacs]] for Windows, e.g. 28.2 to =c:/utils/Emacs= and then install the primary dependencies of this
configuration. Create shortcuts for =runemacs.exe= and =emacsclientw.exe=. Both shortcuts should start *Emacs* from the
home directory and the client should be called as:
=C:\utils\Emacs\bin\emacsclientw.exe -n -a C:\utils\Emacs\bin\runemacs.exe -c=

The main dependencies for *Psimacs* are:
- Python :: Install e.g. [[https://www.python.org/downloads/][Python]] 3.10.8 to =c:/utils/Python310=.
- Msys2 :: Install [[https://www.msys2.org/][MSYS2]] to =c:/utils/msys64=.

This configuration uses *Emacs* >= 27 and is tested with  *Emacs* = 28.2. Clone the git repository into your *.emcas.d*
directory:

#+begin_example
mv ~/.emacs.d ~/.emacs.d.bak
git clone https://github.com/hatlafax/psimacs.git ~/.emacs.d
#+end_example

Now install dependency packages for Python:

#+begin_example
cd c:/utils/python310
python -m pip install pip --upgrade

cd c:/utils/Python310/Scripts
pip install -r ~/.emacs.d/assets/dependencies/python/requirements.txt
#+end_example

Next, install dependency packages for MSYS2. Open the /MSYS2 MinGW 64-bit/ shell and run the following commands:

#+begin_example
pacman -S - < ~/.emacs.d/assets/dependencies/msys2/requirements.txt
#+end_example

Remark: Configure =requirements.txt= as your likeing before running the installation.

Finally, just run *Emacs*.

The only file really needed is the =early-init.el= file. On startup, it reads the file =init.org= and extracts all the
initialization code into the main =init.el= and various additionally =config/init-*.el= files. The created =init.el=
file is then read and evaluated in the further startup procedure. The =init.el= file loads the other =config/init-*.el=
files on evaluation.

Never edit transient file =init.el= or =config/init-*.el= directly. They will be overridden by the next run of
*Psimacs*. Instead modify the =init.org= file to change your configuration.

You can create a HTML document =init.html= of this file by simply typing =C-c C-e h h= in the *Emacs* buffer for
this file. It is recommended to use this =init.html= for browser reading.
This configuration uses *Emacs* >= 27. Clone the git repository into your *.emcas.d* directory

* Usage

The full documentation of the configuration can be found in the =init.org= file. 
The Org exported html file can be visited [[https://hatlafax.github.io/psimacs][here]].

* Dependencies

*Psimacs* does have a number of dependencies to unfold its full potential. The file =init.org= details about them.

* Disclaimer

This is an *Emacs* beginners configuration and the usage is at one's own risk. It is not tested thoroughly. Please
bear in mind.

Many of the configuration settings are borrowed from other similar endeavors out there.

This is work in progress. Sometimes this *Readme* is ahead of times or not yet updated.

* Limitations / Known Issues

- Tested on Windows operating system only

* License (GPL v3)

Copyright (C) 2020-2021 Johannes Brunen (hatlafax@gmx.de)

License: GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
