#+HTML:<div align=center><a href="https://github.com/hatlafax/psimacs"><img alt="Emacs Logo" width="240" height="240" src="https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg"></a>

* psimacs - Yet another Emacs configuration

[[https://github.com/hatlafax/psimacs][https://img.shields.io/badge/Psimacs-3.0-red.svg?style=plastic]]
[[https://www.gnu.org/software/emacs/][https://img.shields.io/badge/GNU%20Emacs-30.2-green.svg?style=plastic]]
[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg?style=plastic]]
[[https://www.msys2.org/][https://img.shields.io/badge/MSYS2-latest-magenta.svg?style=plastic]]

#+HTML:</div>

This is an attempt to create a *Emacs* configuration from the ground up. It has the following objectives:

- Literally programming style. The complete configuration is written in one [[https://orgmode.org/][org-mode]] file.
- Primarily targets the Windows and Linux operating systems. It started on Windows and works very well on that platform.
- Simple to use.
- Provides bootstrapping of used tools on Windows.
- [[https://github.com/raxod502/straight.el][Straight]] package manager.
- Support of [[https://www.dropbox.com/][Dropbox]] configuration and file sharing.
- Classic *Emacs* keyboard handling.
- Use of [[https://github.com/justbur/emacs-which-key][which-key]].
- Use of [[https://github.com/abo-abo/hydra][hydra]].
- Use of [[https://github.com/abo-abo/swiper][ivy]]. I started with ivy and I am quite comfortable with it. Likely, [[https://www.gnu.org/software/emacs/manual/html_mono/ido.html][ido]], [[https://github.com/emacs-helm/helm][helm]] and the more recent incarnations like [[https://github.com/minad/vertico][vertico]] are also worth trying.
- Use of [[https://github.com/bbatsov/projectile][projectile]].
- Use of [[http://company-mode.github.io/][company]].
- Use of [[https://github.com/peter-milliken/ELSE][ELSE]] for programming.
- Use of [[https://github.com/joaotavora/yasnippet][yasnippet]].
- ... and many more packages.
- Focus on ORG, programming and [[https://www.gnu.org/software/auctex/][LaTeX]] text writing.

* Motivation

A lot of *Emacs* configurations can be found on the Internet. Many of them are well crafted and could be used out of
the box. Especially, the great *Emacs* distributions like [[https://www.spacemacs.org/][Spacemacs]], [[https://github.com/hlissner/doom-emacs][Doom-Emacs]] and [[https://github.com/seagle0128/.emacs.d][Centaur-Emacs]] are worth giving it a try.
But I wanted to craft my own configuration that is tailored to my needs and that allows me to learn more about the
vast *Emacs* universe. My configuration it not perfect for everyone, and it will not be able to compete against the big
frameworks that are build by a lot of talented people. So feel free to use it or blame it. I am fine with it.

The name *Psimacs* is arbitrarily. I was in search for a catchy name with just one syllable in front of the *macs*.

* Installation
** Windows
The Powershell script =bootstrap.ps1=, provided in the distribution, is able to bootstrap *Psimacs* and all of its
dependencies into the user's =%HOME%\psimacs= directory. No administrator privileges are required for the installation.
However, considerable disk space is required for the complete installation. *Psimacs* uses the [[https://www.msys2.org/][MSYS2]] *Emacs* exetutable.

Download the raw =booststrap.ps1= file into a temporary directory and run

#+begin_src
.\booststrap.ps1
#+end_src

in a Powershell console.

The *Psimacs* bootstrapping installs the following tools into the =%HOME%\psimacs= directory:

| Tools                 | Remarks                                                                                                  |
|-----------------------+----------------------------------------------------------------------------------------------------------|
| [[https://www.msys2.org/][MSYS2]]                 | *Psimacs* uses the *Emacs* provided by [[https://www.msys2.org/][MSYS2]].                                                                |
| [[https://conemu.github.io/][ConEmu]]                | Optionally, *Psimacs* can install the [[https://conemu.github.io/][ConEmu]] console emulation. Use option =-conemu= to install the console. |
| [[https://openjdk.org/][Java]]                  | *Psimacs* installs the GPL OpenJDK Java distribution provided by Oracle.                                   |
| [[https://languagetool.org][LanguageTool]]          | [[https://languagetool.org][LanguageTool]] is a spell and grammar checker supported by *Psimacs*.                                        |
| [[https://pandoc.org/][pandoc]]                | *Psimacs* uses the universal document converter [[https://pandoc.org/][Pandoc]].                                                    |
| [[https://plantuml.com][plantUML]]              | [[https://plantuml.com][PlantUML]] diagram generation is supported by *Psimacs*.                                                     |
| [[https://www.python.org/][python]]                | *Psimacs* installs [[https://www.python.org/][Python]] and uses a virtual environment created from this installation.                   |
| [[https://www.sumatrapdfreader.org][SumatraPDF]]            | *Psimacs* uses the free SumatraPDF viewer.                                                                 |
| [[https://github.com/hatlafax/ELSE-grammar-compiler][ELSE Grammar Compiler]] | Tool allowing to create ELSE language specification files.                                               |
| [[https://revealjs.com/][Reveal.js]]             | Reveal.js is an open source HTML presentation framework.                                                 |
|-----------------------+----------------------------------------------------------------------------------------------------------|

To get detail help on the options =bootstrap.ps1= provides, do run:

#+begin_src
.\booststrap.ps1 --help
#+end_src

On bootstrapping, *Psimacs* installs the most recent versions of the tools that are known to work
properly in the context of *Psimacs*. Any other tools used by *Psimacs* are installed within the
[[https://www.msys2.org/][MSYS2]] environment, e.g. [[https://www.doxygen.nl/][doxygen]], [[https://www.graphviz.org/][graphviz]] or [[https://mermaid.js.org/][mermaid]].

The bootstrapping operation tries hard to not modify the target system outside of =%HOME%\psimacs= directory,
but there are some exceptions:

- In case that no =%HOME%= variable is defined inside of the active environment, a variable =%HOME%= is created
  and set to value =c:\home\%UserName%=. After that, the =%HOME%= directory is created, if it does not already exists.
- Bootstrapping installs a number of font files into the user's font directory.
- A raw python installation is performed into the local =%HOME%\psimacs= directory. On default a standalone version
  is installed that does not modify the outer system. However, an option exists to take the official python
  MSI installer. This version will  modify the registry.
- A number of desktop shortcuts are created.

After bootstrapping, the [[https://github.com/raxod502/straight.el][Straight]] based *Psimacs* configuration is performed on the very first startup
of *Psimacs*. This process takes a couple of minutes and might asks for confirmation to allow the download of
1. a suitable [[https://github.com/nnicandro/emacs-zmq][emacs-zmq]] binary, and
2. for the [[https://github.com/iqbalansari/emacs-emojify][emacs-emojify]] icons.

*Attention:*
- At least 22 GByte of free disk space is used by the default *Psimacs* installation!
- Performing a *Psimacs* bootstrapping operation is at one's own risk!
- For MSYS2 and for Python many additional packages are installed with *pacman* and *pip*,
  respectively. The list packages are governed by the needs of the author. If you do not
  like to install all of this stuff you have two measures for change:
  - *MSYS2* : Modify the =bootstrap.ps1= file directly before execution. In the block
            /'Bootstrapping $msys64'/ you will find all the steps that governs the *MSYS2*
            installation. Just comment the packages that you do not like or need.
  - *Python* : After cloning of the actual *psimacs* repository from github, a file =requirements.txt=
             will be found in the subdirectory =$HOME/psimacs/psimacs/assets/dependencies/windows/python=.
             This file is installed with Python's *pip* program on default. It is, however,
             possible to provide a user =requirements.txt= file by utilizing the =bootstrap.ps1=
             option =pythonrequirements=.

*Remark:* Windows Powershell typically restricts the execution of scripts. You can
take the following measures in order to get the =bootstrap.ps1= script running:
- Set a proper execution policy for powershell scripts with respect to the user profile:

  #+begin_src powershell
Get-ExecutionPolicy -list
Set-ExecutionPolicy -ExecutionPolicy unrestricted -Scope CurrentUser
  #+end_src

- Downloaded powershell scripts are blocked and not allowed to executed. They need to be unlocked:

  #+begin_src powershell
Unblock-File -Path .\bootstrap.ps1
  #+end_src

Finally, just run *Emacs*.

The only file really needed is the =early-init.el= file. On startup, it reads the file =init.org= and extracts all the
initialization code into the main =init.el= and various additionally =config/init-*.el= files. The created =init.el=
file is then read and evaluated in the further startup procedure. The =init.el= file loads the other =config/init-*.el=
files on evaluation.

Never edit transient file =early-init.el=,  =init.el= or =config/init-*.el= directly. They will be overridden by the next
run of *Psimacs*. Instead modify the =init.org= file in order to change your configuration.

HTML documentation files =init.html= and =keybindings.html= can be found in the directory =$HOME/psimacs/psimacs/docs=.
These files are generated from the corresponing =init.org= and the =keybindings.org= files
by running command =C-c C-e h h=, respectively, in the *Emacs* buffer for these files.

It is recommended to use the =init.html= for reading. From a *Psimacs* session, you can always open this file
with =H-<f1>=.

** Linux
*Psimacs* is able to run on Ubuntu 24.04 LTS. Currently, no automatic installation method for bootstrapping
*Psimacs* exists on this platform.

Install the following parts:

| Part                  | Source                                                   | Installation                                                                            | Destination / Remark                                                       |
|-----------------------+----------------------------------------------------------+-----------------------------------------------------------------------------------------+----------------------------------------------------------------------------|
| *Psimacs*               | =https://github.com/hatlafax/psimacs=                      | =git clone https://github.com/hatlafax/psimacs.git=                                       | =~/psimacs/psimacs=                                                          |
| *LanguageTool*          | =https://languagetool.org/download/=                       | =https://languagetool.org/download/LanguageTool-6.4.zip=                                  | =~/psimacs/LanguageTool=                                                     |
| *Antlr*                 | =https://www.antlr.org/download/antlr-4.13.1-complete.jar= | copy file.                                                                              | =~/psimacs/Antlr=                                                            |
| *ELSE-grammar-compiler* | =https://github.com/hatlafax/ELSE-grammar-compiler=        | =git clone https://github.com/hatlafax/ELSE-grammar-compiler.git=                         | =~/psimacs/ELSE-grammar-compiler=                                            |
| *Sumatra PDF*           | =https://www.sumatrapdfreader.org/free-pdf-reader=         | with /snap/ over the /App Center/ of Ubuntu.                                                |                                                                            |
| Various tools         | ubuntu package manager                                   | see =~/psimacs/psimas/assets/dependencies/ubuntu/linux/requirements_ubuntu_installed.txt= | This file contains all modules that were installed when writing this text. |
| *Python* packages       | pip tool                                                 | see  =~/psimacs/psimas/assets/dependencies/ubuntu/python/requirements_linux_versions.txt= | This file contains all packages installed when writing this text.          |
| *Reveal.js*             | =https://github.com/hakimel/reveal.js=                     | =git clone https://github.com/hakimel/reveal.js.git=                                      | =~/psimacs/psimacs=                                                          |
|-----------------------+----------------------------------------------------------+-----------------------------------------------------------------------------------------+----------------------------------------------------------------------------|

A virtual python environment should be used and can be created by running command  =python3 -m venv ./python-0/venv/=.
This virtual python environment is to be activated before starting *Psimacs*.
There exits better methods, but so far that worked for me.

** Fedora

*Psimacs* is able to run on *Fedora 43*. Basically, the installation steps are identical to the Ubuntu
installation process. Packages are installed with the *dnf* package manager.

** MacOS
Currently, MacOS is also not supported by Psimacs.

* Usage

The full documentation of the configuration can be found in the =init.org= file.
The Org exported html file can be visited [[https://hatlafax.github.io/psimacs][here]].

* Dependencies

*Psimacs* does have a number of dependencies to unfold its full potential. The files =bootstrap.ps1= and
=init.org= details about them.

* Disclaimer

This is an *Emacs* beginners configuration and the usage is at one's own risk. It is not tested thoroughly. Please
bear in mind.

Many of the configuration settings are borrowed from other similar endeavors out there.

This is work in progress. Sometimes this *Readme* is ahead of times or not yet updated.

* Limitations / Known Issues

- Tested on Windows operating system only
- Linux usage on Ubuntu 24.04 LTS and Fedora 43 has only started recently and might have some rough edges.
* License (GPL v3)

Copyright (C) 2020-2021 Johannes Brunen (hatlafax@gmx.de)

License: GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
