#+HTML:<div align=center><a href="https://github.com/hatlafax/psimacs"><img alt="Emacs Logo" width="240" height="240" src="https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg"></a>

* psimacs - Yet another Emacs configuration

[[https://github.com/hatlafax/psimacs][https://img.shields.io/badge/Psimacs-0.1-red.svg?style=plastic]]
[[https://www.gnu.org/software/emacs/][https://img.shields.io/badge/GNU%20Emacs-27.1-green.svg?style=plastic]]
[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg?style=plastic]]

#+HTML:</div>

This is an attempt to create a modern *Emacs* configuration from the ground up. It has the following objectives:

- Use of modern packages and styles
It should be an *Emacs* of the 21. century.
- Literally programming style
The complete configuration is written in one [[https://orgmode.org/][org-mode]] file.
- Primarily target Windows operating system
The reason is that I am solely work on Windows and so I do not know much about the details of other systems.
- Simple to use
- No [[https://github.com/emacs-evil/evil][evil]]
Probably a very good package, that many people do like. However, I am trained with the classic *Emacs* keyboard handling
and I am used to it.
- Use of [[https://github.com/justbur/emacs-which-key][which-key]]
This is a game changer for me.
- Use of [[https://github.com/abo-abo/hydra][hydra]]
And another beautiful package that I like a lot.
- Use of [[https://github.com/abo-abo/swiper][ivy]]
I started with ivy and I am quite comfortable with it. Likely, [[https://www.gnu.org/software/emacs/manual/html_mono/ido.html][ido]] and  [[https://github.com/emacs-helm/helm][helm]] are also worth trying.
- Use of [[https://github.com/bbatsov/projectile][projectile]]
Another great package that I am used to.
- Use of [[http://company-mode.github.io/][company]]
Great text completion framework.
- Use of [[https://github.com/joaotavora/yasnippet][yasnippet]]
- Focus on programming and LaTeX
- And many more...

* Motivation

A lot of *Emacs* configurations can be found on the Internet. Many of them are well crafted and could be used out of
the box. Especially, the great *Emacs* distributions like [[https://www.spacemacs.org/][Spacemacs]], [[https://github.com/hlissner/doom-emacs][Doom-Emacs]] and [[https://github.com/seagle0128/.emacs.d][Centaur-Emacs]] are worth giving a try.
But I wanted to craft my own configuration that is tailored to my needs and that allowed me to learn more about the
vast *Emacs* universe. My configuration it not perfect for everyone and it will not be able to compete against the big
frameworks that are build by a lot of talented people. So feel free to use it or blame it. I am fine with it.

The name *Psimacs* is arbitrarily. I was in search for a catchy name with just one syllable in front of the *macs*.

* Installation

This configuration uses *Emacs* >= 27. Clone the git repository into your *.emcas.d* directory

#+begin_src shell
mv ~/.emacs.d ~/.emacs.d.bak
git clone https://github.com/hatlafax/psimacs.git ~/.emacs.d
#+end_src

and just run *Emacs*.

However, the configuration do have some dependencies that should be installed separately and beforehand of *Psimacs*.
On default the non *Emacs* dependencies are expected to be installed in directory *c:/utils/*.

* Dependencies

The following dependencies should be installed on your computer for *Psimacs*:


* Disclaimer

This is an *Emacs* beginners configuration and the usage is at one's own risk. It is not tested thoroughly. Please
bear in mind.

Many of the configuration settings are borrowed from other similar endeavors out there.

This is work in progress. Sometimes this *Readme* is ahead of times or not yet updated.

* Limitations / Known Issues

- Tested on Windows operating system only

* License (GPL v3)

Copyright (C) 2016 Free Software Foundation, Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
